In [8]:
import pymorphy2
import pandas as pd
from tqdm import tqdm
import string
import numpy as np
import faiss
import os
import fasttext
from transformers import AutoModel, AutoTokenizer
from torch.utils.data import Dataset, DataLoader
import torch

In [2]:
dataset = pd.read_csv('../dataset_2.csv')

In [3]:
import nltk
from nltk.corpus import stopwords
 
nltk.download('stopwords')
print(stopwords.words('russian'))

['и', 'в', 'во', 'не', 'что', 'он', 'на', 'я', 'с', 'со', 'как', 'а', 'то', 'все', 'она', 'так', 'его', 'но', 'да', 'ты', 'к', 'у', 'же', 'вы', 'за', 'бы', 'по', 'только', 'ее', 'мне', 'было', 'вот', 'от', 'меня', 'еще', 'нет', 'о', 'из', 'ему', 'теперь', 'когда', 'даже', 'ну', 'вдруг', 'ли', 'если', 'уже', 'или', 'ни', 'быть', 'был', 'него', 'до', 'вас', 'нибудь', 'опять', 'уж', 'вам', 'ведь', 'там', 'потом', 'себя', 'ничего', 'ей', 'может', 'они', 'тут', 'где', 'есть', 'надо', 'ней', 'для', 'мы', 'тебя', 'их', 'чем', 'была', 'сам', 'чтоб', 'без', 'будто', 'чего', 'раз', 'тоже', 'себе', 'под', 'будет', 'ж', 'тогда', 'кто', 'этот', 'того', 'потому', 'этого', 'какой', 'совсем', 'ним', 'здесь', 'этом', 'один', 'почти', 'мой', 'тем', 'чтобы', 'нее', 'сейчас', 'были', 'куда', 'зачем', 'всех', 'никогда', 'можно', 'при', 'наконец', 'два', 'об', 'другой', 'хоть', 'после', 'над', 'больше', 'тот', 'через', 'эти', 'нас', 'про', 'всего', 'них', 'какая', 'много', 'разве', 'три', 'эту', 'моя', 'впр

[nltk_data] Downloading package stopwords to /home/jovyan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [21]:
tqdm.pandas()

class Data(Dataset):
    def __init__(self, data):
        super().__init__()
        self.data = np.array(data)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        text = self.data[idx]
        return text

class Searcher():
    def __init__(self, data, search_type, b=0.75, k=2, texts=None, inv_index=None):
        self.morph = pymorphy2.MorphAnalyzer()
        self.punctuation = string.punctuation + '…' + '«' + '»' + '—'
        self.stop_words = stopwords.words('russian')
        self.use_lemmatization = search_type == 'bm25_lemm'
        self.search_type = search_type
        
        if search_type == 'vec_fasttext':
            self.vectorizer = fasttext.load_model("../cc.ru.300.bin")
        elif search_type == 'vec_bert':
            self.tokenizer = AutoTokenizer.from_pretrained("cointegrated/rubert-tiny2")
            self.vectorizer = AutoModel.from_pretrained("cointegrated/rubert-tiny2")

        self.k = k
        self.b = b

        self.data = data # исходные данные

        if texts is None:
            print('Preprocessing texts...')
            if search_type == 'vec_bert' or search_type == 'vec_fasttext':
                self.texts = data.text.progress_apply(self.preprocess_text)
            else:
                self.texts = data.text.progress_apply(self.preprocess_text) # очищенные тексты в нормальной форме
                
        else:
            self.texts = texts

        if inv_index is None:
            print('Counting inverted index...')
            
            if search_type == 'vec_fasttext':
                texts_vectorized = np.zeros([len(self.texts), self.vectorizer.get_dimension()])
                for doc_id, doc in enumerate(tqdm(self.texts)):
                    
                    texts_vectorized[doc_id] = self.vectorizer[str(doc)]

                inv_index = faiss.IndexFlatL2(texts_vectorized.shape[1])
                inv_index.add(texts_vectorized)

                faiss.write_index(inv_index, "../vec.index")
                
            elif search_type == 'vec_bert':
                
                embeddings = self.vectorize(self.texts)

            elif search_type == 'bm25_lemm':
                inv_index = {}

                for doc_id, doc in enumerate(tqdm(self.texts)):
                    tokens = doc.split()
                    for token in tokens:
                        if token in inv_index:
                            inv_index[token].add(doc_id)
                        else:
                            inv_index[token] = set([doc_id])
            else:
                raise ValueError()
        
        self.inv_index = inv_index
    
    def vectorize(self, df):
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        print(f"{device} is used")
        self.vectorizer.to(device)
        self.vectorizer.eval()
        ldr_data = Data(data=df)
        loader = DataLoader(dataset=ldr_data, shuffle=False, batch_size=min([10, len(df)]))
        embeddings = []
        with torch.no_grad():
            for i, inputs in tqdm(enumerate(loader)):
                batch = self.tokenizer(list(inputs), truncation=True, padding=True, return_tensors='pt', max_length=24)
                input_ids = batch['input_ids']
                input_ids = input_ids.to(device, dtype=torch.long)
                batch['input_ids'] = input_ids

                token_type_ids = batch['token_type_ids']
                token_type_ids = token_type_ids.to(device, dtype=torch.long)
                batch['token_type_ids'] = token_type_ids

                attention_mask = batch['attention_mask']
                attention_mask = attention_mask.to(device, dtype=torch.long)
                batch['attention_mask'] = attention_mask

                preds = self.vectorizer(**batch)
                preds = mean_pooling(preds, attention_mask)
                outputs = preds.cpu().detach().numpy()
                embeddings.extend(outputs)
        
        return embeddings

    def preprocess_text(self, text):
        tokens = str(text).lower().translate(str.maketrans('', '', self.punctuation)).split()
        res = ''

        if self.use_lemmatization:
            for token in tokens:
                p = self.morph.parse(token)[0].normal_form
                if p not in self.stop_words:
                    res += ' ' + p
        else:
            for token in tokens:
                if token not in self.stop_words:
                    res += ' ' + token
        
        return res


    def idf(self, terms, documents, eps=-0.01):
        idfs = np.asarray([len(documents) / (len(self.inv_index[term]) + eps) for term in terms])
        return np.log(idfs)


    def tf(self, terms, doc_ids):
        # можно посплитить текст в init и не сплитить каждый раз
        def count(text):
            freqs = dict.fromkeys(terms, 0)
            text = text.split() 
            for term in text:
                if term in freqs.keys():
                    freqs[term] += 1
            
            return np.asarray([term_freq[1] for term_freq in freqs.items()]) / len(text)

        docs = self.texts[doc_ids]

        return np.stack(docs.apply(count).values)
    
    def tf_idf(self, terms, documents):
        tf_scores = self.tf(terms, documents)
        idf_scores = self.idf(terms, documents)

        scores = tf_scores * idf_scores
        return scores

    def bm25(self, terms, documents):
        
        tf_scores = self.tf(terms, documents)
        idf_scores = self.idf(terms, documents)
        lens = self.texts[documents].apply(lambda x: len(x.split())).to_numpy()

        scores = np.zeros(lens.shape)
        for i, term in enumerate(terms):
            a = (tf_scores[:, i] * (self.k + 1))
            b = (tf_scores[:, i] + self.k * (1 - self.b + self.b * lens / lens.mean()))
            c = idf_scores[i]
            scores += a / b * c

        return scores

    def search(self, query):
        if self.search_type != 'vec_fasttext':
            terms = self.preprocess_text(query).split()

            global_ids = set()
            for term in terms:
                global_ids.update(self.inv_index[term])

            global_ids = np.asarray(list(global_ids))
            scores = self.bm25(terms, global_ids)#.sum(axis=1)

            local_ids = np.argsort(scores, axis=0).squeeze() # сортируем документы по возрастанию tf-idf
            

            return self.data.iloc[global_ids[local_ids][-10:]]
        
        else:
            query_vector = self.vectorizer[query]

            distances, indicies = self.inv_index.search(np.expand_dims(query_vector, 0), 10)

            print(distances)
            print(indicies[0])

            return self.data.iloc[indicies[0]]
        
        

In [22]:
s = Searcher(dataset, search_type='vec_fasttext')

Preprocessing texts...


100%|████████████████████████████████████████████████████████████████████████████| 10385/10385 [00:35<00:00, 295.04it/s]


Counting inverted index...


100%|████████████████████████████████████████████████████████████████████████████| 10385/10385 [00:37<00:00, 274.26it/s]


In [ ]:
texts = s.texts

In [29]:
s.search('Зорот (Xoroth) — мир из вселенной Warcraft. Эта планета принадлежит Пылающему Легиону, в частности, натрезимам, и является родиной коней погибели, которых чернокнижники используют в качестве верховых лошадей.')

[[0.00336832 0.00585805 0.00588941 0.00591027 0.00594001 0.00594629
  0.00595441 0.00595623 0.00596606 0.00597592]]
[6976 9864 1288 8664 9850 6135 3309 5728 1092 5097]


Unnamed: 0              title  \
6976        6976              Зорот   
9864        9864               Атон   
1288        1288             Астрал   
8664        8664         Чужое небо   
9850        9850              Иштар   
6135        6135      Верховный бог   
3309        3309               Оман   
5728        5728  Коробочка фотонов   
1092        1092             Венера   
5097        5097           Недотанк   

                                                   link  \
6976               /wiki/%D0%97%D0%BE%D1%80%D0%BE%D1%82   
9864                     /wiki/%D0%90%D1%82%D0%BE%D0%BD   
1288         /wiki/%D0%90%D1%81%D1%82%D1%80%D0%B0%D0%BB   
8664  /wiki/%D0%A7%D1%83%D0%B6%D0%BE%D0%B5_%D0%BD%D0...   
9850               /wiki/%D0%98%D1%88%D1%82%D0%B0%D1%80   
6135  /wiki/%D0%92%D0%B5%D1%80%D1%85%D0%BE%D0%B2%D0%...   
3309                     /wiki/%D0%9E%D0%BC%D0%B0%D0%BD   
5728  /wiki/%D0%9A%D0%BE%D1%80%D0%BE%D0%B1%D0%BE%D1%...   
1092         /wiki/%D0%92%D0%B5%D0%BD%D0%B5%D1%80%D0%B0   
5097  /wiki/%D0%9D%D0%B5%D0%B4%D0%BE%D1%82%D0%B0%D0%...   

                                                   text  
6976  Зорот (Xoroth) — мир из вселенной Warcraft. Эт...  
9864  Атон — египетский бог в форме солнечного диска...  
1288  Астрал (Тонкий мир, Незримый мир, и т. д., пет...  
8664  В небе сиял Юпитер — стояло полнолуние, вернее...  
9850  Иштар, также известная как Инанна, Астарта (ра...  
6135  Слушайте слово мое, и боги небес, и богини:  Я...  
3309  Оман — унылая страна кагбе в регионе Персидско...  
5728  Коробочка фотонов (реже мешок или весовые част...  
1092  Следующая по влиянию на умы фантастов планета ...  
5097  Основные составляющие танка — умение держать у...

In [23]:
s.search('Зорот (Xoroth) — мир из вселенной Warcrafxt. Эта планета принадлежит Пылающему Легиону, в частности, натрезимам, и является родиной коней погибели, которых чернокнижники используют в качестве верховых лошадей.')

[[0.00336832 0.00585805 0.00588941 0.00591027 0.00594001 0.00594629
  0.00595441 0.00595623 0.00596606 0.00597592]]
[6976 9864 1288 8664 9850 6135 3309 5728 1092 5097]


Unnamed: 0              title  \
6976        6976              Зорот   
9864        9864               Атон   
1288        1288             Астрал   
8664        8664         Чужое небо   
9850        9850              Иштар   
6135        6135      Верховный бог   
3309        3309               Оман   
5728        5728  Коробочка фотонов   
1092        1092             Венера   
5097        5097           Недотанк   

                                                   link  \
6976               /wiki/%D0%97%D0%BE%D1%80%D0%BE%D1%82   
9864                     /wiki/%D0%90%D1%82%D0%BE%D0%BD   
1288         /wiki/%D0%90%D1%81%D1%82%D1%80%D0%B0%D0%BB   
8664  /wiki/%D0%A7%D1%83%D0%B6%D0%BE%D0%B5_%D0%BD%D0...   
9850               /wiki/%D0%98%D1%88%D1%82%D0%B0%D1%80   
6135  /wiki/%D0%92%D0%B5%D1%80%D1%85%D0%BE%D0%B2%D0%...   
3309                     /wiki/%D0%9E%D0%BC%D0%B0%D0%BD   
5728  /wiki/%D0%9A%D0%BE%D1%80%D0%BE%D0%B1%D0%BE%D1%...   
1092         /wiki/%D0%92%D0%B5%D0%BD%D0%B5%D1%80%D0%B0   
5097  /wiki/%D0%9D%D0%B5%D0%B4%D0%BE%D1%82%D0%B0%D0%...   

                                                   text  
6976  Зорот (Xoroth) — мир из вселенной Warcraft. Эт...  
9864  Атон — египетский бог в форме солнечного диска...  
1288  Астрал (Тонкий мир, Незримый мир, и т. д., пет...  
8664  В небе сиял Юпитер — стояло полнолуние, вернее...  
9850  Иштар, также известная как Инанна, Астарта (ра...  
6135  Слушайте слово мое, и боги небес, и богини:  Я...  
3309  Оман — унылая страна кагбе в регионе Персидско...  
5728  Коробочка фотонов (реже мешок или весовые част...  
1092  Следующая по влиянию на умы фантастов планета ...  
5097  Основные составляющие танка — умение держать у...

In [30]:
s.search('война судного дня')

[[0.100796   0.10161673 0.10191935 0.10303252 0.10348049 0.10446803
  0.10454261 0.10461313 0.10477074 0.10478412]]
[ 4910  1328  7344  8077  1861 10362  5706  6196  9515  3815]


Unnamed: 0                        title  \
4910         4910                        Циник   
1328         1328                       Сотона   
7344         7344                 MrGoodmobile   
8077         8077                       Смегма   
1861         1861  Копипаста:Lurkmore:Contacts   
10362       10362   Евгений Викторович Кошевой   
5706         5706                   Тряпка-кун   
6196         6196                      Нирвана   
9515         9515          Надписи на снарядах   
3815         3815                  Шулхан Арух   

                                                    link  \
4910                /wiki/%D0%A6%D0%B8%D0%BD%D0%B8%D0%BA   
1328          /wiki/%D0%A1%D0%BE%D1%82%D0%BE%D0%BD%D0%B0   
7344                                  /wiki/MrGoodmobile   
8077          /wiki/%D0%A1%D0%BC%D0%B5%D0%B3%D0%BC%D0%B0   
1861   /wiki/%D0%9A%D0%BE%D0%BF%D0%B8%D0%BF%D0%B0%D1%...   
10362  /wiki/%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%...   
5706   /wiki/%D0%A2%D1%80%D1%8F%D0%BF%D0%BA%D0%B0-%D0...   
6196    /wiki/%D0%9D%D0%B8%D1%80%D0%B2%D0%B0%D0%BD%D0%B0   
9515   /wiki/%D0%9D%D0%B0%D0%B4%D0%BF%D0%B8%D1%81%D0%...   
3815   /wiki/%D0%A8%D1%83%D0%BB%D1%85%D0%B0%D0%BD_%D0...   

                                                    text  
4910   Циники (Циничные люди) — приверженцы цинизма, ...  
1328   Рыба гниёт с головы, но чистят её с хвоста.  С...  
7344   MrGoodmobile — укропский видеоблогер, снимающи...  
8077   Смегма (англ. Dick Cheese, более известна как ...  
1861   Официальным пресс-секретарем Луркоморья являет...  
10362  Евгений Викторович Кошевой - лысый придурок и ...  
5706   Тряпка-кун — одна из самых громких деанонимиза...  
6196   Нирвана — строго говоря, раем не является. В Б...  
9515   Надписи на снарядах — явление, при котором на ...  
3815   Я задался вопросом: на каком основании евреи б...

In [27]:
dataset.iloc[7840].text

'Это страница неоднозначности. Ниже можно прочитать список значений и выбрать из них интересующее. Бывает:  смешной по-настоящему страшный'

In [31]:
s.search('украинский кризис')

[[0.06356399 0.06866173 0.07268341 0.07331744 0.0736462  0.07372062
  0.07374732 0.07375086 0.07394659 0.07399531]]
[ 3650  9429  9609 10333  9268  1755  2436 10357   649  4280]


Unnamed: 0                                              title  \
3650         3650                                             Кризис   
9429         9429                                  Украинский кризис   
9609         9609                            Запрет айфонов в России   
10333       10333                                         Новороссия   
9268         9268                                       Я случайно X   
1755         1755                        Шаблон:Спасено с Лурка/More   
2436         2436                                             Крикун   
10357       10357                                     Игорь Мосийчук   
649           649  Почему титаны слишком большого размера? (Хрони...   
4280         4280                          Закрытие Сохнута в России   

                                                    link  \
3650          /wiki/%D0%9A%D1%80%D0%B8%D0%B7%D0%B8%D1%81   
9429   /wiki/%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D1%...   
9609   /wiki/%D0%97%D0%B0%D0%BF%D1%80%D0%B5%D1%82_%D0...   
10333  /wiki/%D0%9D%D0%BE%D0%B2%D0%BE%D1%80%D0%BE%D1%...   
9268   /wiki/%D0%AF_%D1%81%D0%BB%D1%83%D1%87%D0%B0%D0...   
1755   /wiki/%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD:%D0...   
2436          /wiki/%D0%9A%D1%80%D0%B8%D0%BA%D1%83%D0%BD   
10357  /wiki/%D0%98%D0%B3%D0%BE%D1%80%D1%8C_%D0%9C%D0...   
649    /wiki/%D0%9F%D0%BE%D1%87%D0%B5%D0%BC%D1%83_%D1...   
4280   /wiki/%D0%97%D0%B0%D0%BA%D1%80%D1%8B%D1%82%D0%...   

                                                    text  
3650   Большой пиздец не за горами, и волны кризисов ...  
9429   Украинский кризис — политический кризис с учас...  
9609   Запрет айфонов в России — новая интересная ини...  
10333  Новороссия — название для проекта независимого...  
9268   Я случайно X (англ. I accidentally X) — мем ан...  
1755   "Вдруг война, а я уставший..." .onion 1 мая 1....  
2436   Крикун (Выпускник, Яростный Школьник, Кри-кун)...  
10357  Украинские клоуны уже весь мир смешат, то с па...  
649    Почему титаны слишком большого размера? — расп...  
4280   Закрытие Сохнута в России — закрытие еврейског...

In [33]:
s.search('война в украине')

[[0.15854478 0.15978475 0.16024865 0.16064066 0.1608152  0.16151662
  0.1615301  0.16248792 0.16379516 0.16472024]]
[ 1009  1008  8077  9429  1328 10362  5155  7344 10357 10342]


Unnamed: 0                       title  \
1009         1009               Алфавит Двача   
1008         1008    Мост в Терабитию/Алфавит   
8077         8077                      Смегма   
9429         9429           Украинский кризис   
1328         1328                      Сотона   
10362       10362  Евгений Викторович Кошевой   
5155         5155  Внутри меньше, чем снаружи   
7344         7344                MrGoodmobile   
10357       10357              Игорь Мосийчук   
10342       10342                  Закарпатье   

                                                    link  \
1009   /wiki/%D0%90%D0%BB%D1%84%D0%B0%D0%B2%D0%B8%D1%...   
1008   /wiki/%D0%9C%D0%BE%D1%81%D1%82_%D0%B2_%D0%A2%D...   
8077          /wiki/%D0%A1%D0%BC%D0%B5%D0%B3%D0%BC%D0%B0   
9429   /wiki/%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D1%...   
1328          /wiki/%D0%A1%D0%BE%D1%82%D0%BE%D0%BD%D0%B0   
10362  /wiki/%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%...   
5155   /wiki/%D0%92%D0%BD%D1%83%D1%82%D1%80%D0%B8_%D0...   
7344                                  /wiki/MrGoodmobile   
10357  /wiki/%D0%98%D0%B3%D0%BE%D1%80%D1%8C_%D0%9C%D0...   
10342  /wiki/%D0%97%D0%B0%D0%BA%D0%B0%D1%80%D0%BF%D0%...   

                                                    text  
1009   Эта галерея алфавита Двача. В уютненьком есть ...  
1008   Эта подстатья об алфавите АнныСофии. В уютнень...  
8077   Смегма (англ. Dick Cheese, более известна как ...  
9429   Украинский кризис — политический кризис с учас...  
1328   Рыба гниёт с головы, но чистят её с хвоста.  С...  
10362  Евгений Викторович Кошевой - лысый придурок и ...  
5155   В компьютерных играх нередко можно вломиться в...  
7344   MrGoodmobile — укропский видеоблогер, снимающи...  
10357  Украинские клоуны уже весь мир смешат, то с па...  
10342  Закарпатье — самый западный и самый дальний от...

In [42]:
s.search('конституция российской федерации')

[[0.02322684 0.0241304  0.02451413 0.02452654 0.02470964 0.02480914
  0.02483547 0.02484737 0.02490055 0.02491833]]
[ 2203  3452  3234  5298  3201  7264  2825  1034  4507 10200]


Unnamed: 0                                title  \
2203         2203                            Педерация   
3452         3452                          Брайтон-Бич   
3234         3234          Дружественные страны России   
5298         5298                Posmotre.li:Навигация   
3201         3201                   Привислинский край   
7264         7264                           Иван Лизан   
2825         2825                        Герман Bealik   
1034         1034  Старая копипаста:Ичуньская Компания   
4507         4507                                 LMAO   
10200       10200            Сборная России по футболу   

                                                    link  \
2203   /wiki/%D0%9F%D0%B5%D0%B4%D0%B5%D1%80%D0%B0%D1%...   
3452   /wiki/%D0%91%D1%80%D0%B0%D0%B9%D1%82%D0%BE%D0%...   
3234   /wiki/%D0%94%D1%80%D1%83%D0%B6%D0%B5%D1%81%D1%...   
5298   /wiki/Posmotre.li:%D0%9D%D0%B0%D0%B2%D0%B8%D0%...   
3201   /wiki/%D0%9F%D1%80%D0%B8%D0%B2%D0%B8%D1%81%D0%...   
7264   /wiki/%D0%98%D0%B2%D0%B0%D0%BD_%D0%9B%D0%B8%D0...   
2825   /wiki/%D0%93%D0%B5%D1%80%D0%BC%D0%B0%D0%BD_Bealik   
1034   /wiki/%D0%A1%D1%82%D0%B0%D1%80%D0%B0%D1%8F_%D0...   
4507                                          /wiki/LMAO   
10200  /wiki/%D0%A1%D0%B1%D0%BE%D1%80%D0%BD%D0%B0%D1%...   

                                                    text  
2203   Педерация — распространённое искажение слова «...  
3452   Брайтон-Бич (Маленькая Одесса) — русско-украин...  
3234   Дружественные страны России, — признанные офиц...  
5298   Мета Основы Основы Жанры Сюжет Производное тво...  
3201   Привислинский край (также Привислянский край; ...  
7264   Иван Лизан (ivan_lizan) — российский экономист...  
2825   Герман Bealik — пользователь Ответы@mail.ru, н...  
1034   250-я Ичуньская Приграничная Синтетическая Тор...  
4507   LMAO — аббревиатура от англоязычной фразы «lau...  
10200  Сборная России по футболу — собирательное назв...

In [34]:
s.search('видеоигры')

[[0.37629652 0.3780882  0.37857202 0.37966228 0.37989593 0.3799671
  0.37997022 0.38007995 0.38013956 0.38020948]]
[5038 7780 6796  891 6971 6772 6643 8914 5037 7155]


Unnamed: 0                    title  \
5038        5038                Симулятор   
7780        7780                   Фанарт   
6796        6796     Киновселенная Марвел   
891          891   Ой-вей, нiнгенъ сакеръ   
6971        6971  Расы вселенной Warcraft   
6772        6772               Метрополис   
6643        6643    Sid Meier's Starships   
8914        8914          Джейсон Стейтем   
5037        5037             Метроидвания   
7155        7155                 Garfield   

                                                   link  \
5038  /wiki/%D0%A1%D0%B8%D0%BC%D1%83%D0%BB%D1%8F%D1%...   
7780         /wiki/%D0%A4%D0%B0%D0%BD%D0%B0%D1%80%D1%82   
6796  /wiki/%D0%9A%D0%B8%D0%BD%D0%BE%D0%B2%D1%81%D0%...   
891   /wiki/%D0%9E%D0%B9-%D0%B2%D0%B5%D0%B9,_%D0%BDi...   
6971  /wiki/%D0%A0%D0%B0%D1%81%D1%8B_%D0%B2%D1%81%D0...   
6772  /wiki/%D0%9C%D0%B5%D1%82%D1%80%D0%BE%D0%BF%D0%...   
6643                      /wiki/Sid_Meier%27s_Starships   
8914  /wiki/%D0%94%D0%B6%D0%B5%D0%B9%D1%81%D0%BE%D0%...   
5037  /wiki/%D0%9C%D0%B5%D1%82%D1%80%D0%BE%D0%B8%D0%...   
7155                                     /wiki/Garfield   

                                                   text  
5038  Симулятор — жанр компьютерных игр, суть которы...  
7780  Фанарт (fan art, англ. «фанатское искусство») ...  
6796  Кинематографическая вселенная Марвел (Marvel C...  
891   Ой-вей, нiнгенъ сакеръ (moon. へいへい人間賛歌) — мем ...  
6971  Люди Дворфы Ночные эльфы Гномы Дренеи Воргены ...  
6772  Это страница неоднозначности. Ниже можно прочи...  
6643  Sid Meier’s Starships — сиквел к Sid Meier’s C...  
8914  Джейсон Стейтем (англ. Jason Statham; род. 26 ...  
5037  Метроидвания — поджанр платформеров с геймплее...  
7155  «Гарфилд» (англ. Garfield) — это газетный коми...

In [50]:
s.search('все прогрессивное человечество')

[[0.02552456 0.02793368 0.0279752  0.02817386 0.02845105 0.02851618
  0.02867845 0.02883737 0.0288555  0.02889591]]
[7646 2254 9776 3182 5842 4741 4345 9775 5622 4682]


Unnamed: 0                                  title  \
7646        7646         Всё прогрессивное человечество   
2254        2254  Сколько человек может прожить без сна   
9776        9776                            Воскрешение   
3182        3182               Англосаксонские владения   
5842        5842                        Дизайнеры жизни   
4741        4741                       Homo overclocked   
4345        4345  Еврейский музей и центр толерантности   
9775        9775                                Владыка   
5622        5622                     Социальный рейтинг   
4682        4682                               Нейтралы   

                                                   link  \
7646  /wiki/%D0%92%D1%81%D1%91_%D0%BF%D1%80%D0%BE%D0...   
2254  /wiki/%D0%A1%D0%BA%D0%BE%D0%BB%D1%8C%D0%BA%D0%...   
9776  /wiki/%D0%92%D0%BE%D1%81%D0%BA%D1%80%D0%B5%D1%...   
3182  /wiki/%D0%90%D0%BD%D0%B3%D0%BB%D0%BE%D1%81%D0%...   
5842  /wiki/%D0%94%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D0%...   
4741                             /wiki/Homo_overclocked   
4345  /wiki/%D0%95%D0%B2%D1%80%D0%B5%D0%B9%D1%81%D0%...   
9775   /wiki/%D0%92%D0%BB%D0%B0%D0%B4%D1%8B%D0%BA%D0%B0   
5622  /wiki/%D0%A1%D0%BE%D1%86%D0%B8%D0%B0%D0%BB%D1%...   
4682  /wiki/%D0%9D%D0%B5%D0%B9%D1%82%D1%80%D0%B0%D0%...   

                                                   text  
7646  Всё прогрессивное человечество — советский мем...  
2254  Сколько человек может прожить без сна — распро...  
9776  Воскрешение — возвращение человека в жизни пос...  
3182  Англосаксонские владения — союз государств, ко...  
5842  Дизайнеры жизни (Life Planners) — конспирологи...  
4741  Homo overclocked (человек разогнанный) — харак...  
4345  Еврейский музей и центр толерантности — москов...  
9775  Владыка — мощное слово, обозначающее действите...  
5622  Социальный рейтинг (Социальный кредит) — важны...  
4682  Нейтралы — люди, придерживающиеся политики ней...

In [37]:
s.search('автомобили')

[[0.24243669 0.24249664 0.24253696 0.24265097 0.24265297 0.24265862
  0.24276732 0.24287319 0.243154   0.24320997]]
[ 5298 10377  9765  3602 10305  5251  3464  9225  2116  9588]


Unnamed: 0                          title  \
5298         5298          Posmotre.li:Навигация   
10377       10377                   Daewoo Lanos   
9765         9765   Четыре всадника Апокалипсиса   
3602         3602  Кинжал (гиперзвуковая ракета)   
10305       10305                            ТАЗ   
5251         5251          Ракета летит медленно   
3464         3464               Охотничьи угодья   
9225         9225             New School (сингл)   
2116         2116                     Вышиватник   
9588         9588                            HTC   

                                                    link  \
5298   /wiki/Posmotre.li:%D0%9D%D0%B0%D0%B2%D0%B8%D0%...   
10377                                 /wiki/Daewoo_Lanos   
9765   /wiki/%D0%A7%D0%B5%D1%82%D1%8B%D1%80%D0%B5_%D0...   
3602   /wiki/%D0%9A%D0%B8%D0%BD%D0%B6%D0%B0%D0%BB_(%D...   
10305                           /wiki/%D0%A2%D0%90%D0%97   
5251   /wiki/%D0%A0%D0%B0%D0%BA%D0%B5%D1%82%D0%B0_%D0...   
3464   /wiki/%D0%9E%D1%85%D0%BE%D1%82%D0%BD%D0%B8%D1%...   
9225   /wiki/New_School_(%D1%81%D0%B8%D0%BD%D0%B3%D0%BB)   
2116   /wiki/%D0%92%D1%8B%D1%88%D0%B8%D0%B2%D0%B0%D1%...   
9588                                           /wiki/HTC   

                                                    text  
5298   Мета Основы Основы Жанры Сюжет Производное тво...  
10377  Daewoo Lanos (редк. Doninvest Assol, хохл. Sen...  
9765   Четыре всадника Апокалипсиса — концепт четырёх...  
3602   Кинжал(или 9-А-7660, Х-47М2) — сверхмощная кул...  
10305  Тазы (ВАЗ-Лада)- адские создания от не менее а...  
5251   Чак Норрис может поймать летящую в него ракету...  
3464   Охотничьи угодья — та или иная территория, выд...  
9225   New School — сингл российских рэп-исполнителей...  
2116   Вышиватник (укр. вишіватнік, от слов «вышиванк...  
9588   HTC Corporation (бывшая High Tech Computer Cor...